/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutManifestoRouteImport } from './routes/about.manifesto'
import { Route as AboutPressRouteImport } from './routes/about.press'
import { Route as AboutStoryRouteImport } from './routes/about.story'
import { Route as AboutValuesRouteImport } from './routes/about.values'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const AboutManifestoRoute = AboutManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => AboutRoute,
} as any)
const AboutPressRoute = AboutPressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => AboutRoute,
} as any)
const AboutStoryRoute = AboutStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => AboutRoute,
} as any)
const AboutValuesRoute = AboutValuesRouteImport.update({
  id: '/values',
  path: '/values',
  getParentRoute: () => AboutRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/capabilities': typeof CapabilitiesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRouteWithChildren
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/about/manifesto': typeof AboutManifestoRoute
  '/about/press': typeof AboutPressRoute
  '/about/story': typeof AboutStoryRoute
  '/about/values': typeof AboutValuesRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/about/': typeof AboutIndexRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/about/manifesto': typeof AboutManifestoRoute
  '/about/press': typeof AboutPressRoute
  '/about/story': typeof AboutStoryRoute
  '/about/values': typeof AboutValuesRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/about': typeof AboutIndexRoute
  '/journal': typeof JournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/capabilities': typeof CapabilitiesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRouteWithChildren
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/about/manifesto': typeof AboutManifestoRoute
  '/about/press': typeof AboutPressRoute
  '/about/story': typeof AboutStoryRoute
  '/about/values': typeof AboutValuesRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/about/': typeof AboutIndexRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/capabilities'
    | '/careers'
    | '/contact'
    | '/journal'
    | '/process'
    | '/services'
    | '/team'
    | '/about/manifesto'
    | '/about/press'
    | '/about/story'
    | '/about/values'
    | '/journal/$slug'
    | '/about/'
    | '/journal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capabilities'
    | '/careers'
    | '/contact'
    | '/process'
    | '/services'
    | '/team'
    | '/about/manifesto'
    | '/about/press'
    | '/about/story'
    | '/about/values'
    | '/journal/$slug'
    | '/about'
    | '/journal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/capabilities'
    | '/careers'
    | '/contact'
    | '/journal'
    | '/process'
    | '/services'
    | '/team'
    | '/about/manifesto'
    | '/about/press'
    | '/about/story'
    | '/about/values'
    | '/journal/$slug'
    | '/about/'
    | '/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  CapabilitiesRoute: typeof CapabilitiesRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  JournalRoute: typeof JournalRouteWithChildren
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/manifesto': {
      id: '/about/manifesto'
      path: '/manifesto'
      fullPath: '/about/manifesto'
      preLoaderRoute: typeof AboutManifestoRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/press': {
      id: '/about/press'
      path: '/press'
      fullPath: '/about/press'
      preLoaderRoute: typeof AboutPressRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/story': {
      id: '/about/story'
      path: '/story'
      fullPath: '/about/story'
      preLoaderRoute: typeof AboutStoryRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/values': {
      id: '/about/values'
      path: '/values'
      fullPath: '/about/values'
      preLoaderRoute: typeof AboutValuesRouteImport
      parentRoute: typeof AboutRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
  }
}

interface AboutRouteChildren {
  AboutManifestoRoute: typeof AboutManifestoRoute
  AboutPressRoute: typeof AboutPressRoute
  AboutStoryRoute: typeof AboutStoryRoute
  AboutValuesRoute: typeof AboutValuesRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutManifestoRoute: AboutManifestoRoute,
  AboutPressRoute: AboutPressRoute,
  AboutStoryRoute: AboutStoryRoute,
  AboutValuesRoute: AboutValuesRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  CapabilitiesRoute: CapabilitiesRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  JournalRoute: JournalRouteWithChildren,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
